## Example Agent Play

In [1]:
import time

from game import Game2048
game = Game2048({"grid_size": 4})
t0 = time.time()
for _ in range(1000):
    g = game.clone()
    g.get_available_moves()
print(f"1000 clone+get_moves: {(time.time()-t0)*1000:.0f} ms")

1000 clone+get_moves: 136 ms


In [1]:
from game import Game2048, Action
import numpy as np

config = {
    'grid_size': 4,
    'tile_2_probability': 0.9,
    'initial_tiles': 2,
    'random_seed': 42,
}
game = Game2048(config)

step = 0
while not game.is_game_over():
    available = game.get_available_moves()
    if not available:
        break

    action = np.random.choice(available)
    valid, reward = game.move(action)
    step += 1

    print(f"--- Step {step} | Action: {action.name} | Reward: {reward} | Score: {game.get_score()} ---")
    print(game.get_state())
    print()

print(f"Game Over! Final Score: {game.get_score()} in {step} steps")

pygame 2.6.1 (SDL 2.28.4, Python 3.11.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
--- Step 1 | Action: UP | Reward: 0 | Score: 0 ---
[[0 0 2 2]
 [0 0 2 0]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 2 | Action: LEFT | Reward: 4 | Score: 4 ---
[[4 0 0 0]
 [2 0 0 0]
 [2 0 0 0]
 [0 0 0 0]]

--- Step 3 | Action: UP | Reward: 4 | Score: 8 ---
[[4 0 0 0]
 [4 2 0 0]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 4 | Action: RIGHT | Reward: 0 | Score: 8 ---
[[0 0 0 4]
 [0 0 4 2]
 [2 0 0 0]
 [0 0 0 0]]

--- Step 5 | Action: RIGHT | Reward: 0 | Score: 8 ---
[[0 0 0 4]
 [0 0 4 2]
 [0 0 0 2]
 [0 0 0 4]]

--- Step 6 | Action: DOWN | Reward: 4 | Score: 12 ---
[[0 0 0 0]
 [0 0 0 4]
 [0 0 0 4]
 [0 2 4 4]]

--- Step 7 | Action: RIGHT | Reward: 8 | Score: 20 ---
[[0 0 0 0]
 [0 0 0 4]
 [0 0 2 4]
 [0 0 2 8]]

--- Step 8 | Action: UP | Reward: 12 | Score: 32 ---
[[2 0 4 8]
 [0 0 0 8]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 9 | Action: LEFT | Reward: 0 | Score: 32 ---
[[2 4 8 0]
 [8 0 0 0]
 [0 0 0 0]
 [0 2 0

In [2]:
from game import Game2048, Action
import numpy as np

config = {
    'grid_size': 4,
    'tile_2_probability': 0.9,
    'initial_tiles': 2,
    'random_seed': 42,
}

game = Game2048(config)
step = 0

while not game.is_game_over():
    available = game.get_available_moves()
    if not available:
        break

    # simulate each move on a clone, pick highest reward
    best_action = None
    best_reward = -1
    for action in available:
        sim = game.clone()
        _, reward = sim.move(action)
        if reward > best_reward:
            best_reward = reward
            best_action = action

    # tie-break: if all rewards are 0, pick randomly
    if best_reward == 0:
        best_action = available[np.random.randint(len(available))]

    valid, reward = game.move(best_action)
    step += 1
    print(f"--- Step {step} | Action: {best_action.name} | Reward: {reward} | Score: {game.get_score()} ---")
    print(game.get_state())
    print()

print(f"Game Over! Final Score: {game.get_score()} in {step} steps")

--- Step 1 | Action: RIGHT | Reward: 0 | Score: 0 ---
[[0 0 2 0]
 [0 0 0 2]
 [0 0 0 0]
 [0 0 0 2]]

--- Step 2 | Action: UP | Reward: 4 | Score: 4 ---
[[0 0 2 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 2 0]]

--- Step 3 | Action: UP | Reward: 4 | Score: 8 ---
[[0 0 4 4]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 4 | Action: LEFT | Reward: 8 | Score: 16 ---
[[8 0 2 0]
 [2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 5 | Action: DOWN | Reward: 0 | Score: 16 ---
[[0 0 0 0]
 [0 0 0 2]
 [8 0 0 0]
 [2 0 2 0]]

--- Step 6 | Action: LEFT | Reward: 4 | Score: 20 ---
[[0 2 0 0]
 [2 0 0 0]
 [8 0 0 0]
 [4 0 0 0]]

--- Step 7 | Action: RIGHT | Reward: 0 | Score: 20 ---
[[0 0 0 2]
 [0 2 0 2]
 [0 0 0 8]
 [0 0 0 4]]

--- Step 8 | Action: UP | Reward: 4 | Score: 24 ---
[[2 2 0 4]
 [0 0 0 8]
 [0 0 0 4]
 [0 0 0 0]]

--- Step 9 | Action: LEFT | Reward: 4 | Score: 28 ---
[[4 4 0 0]
 [8 0 0 0]
 [4 0 0 2]
 [0 0 0 0]]

--- Step 10 | Action: LEFT | Reward: 8 | Score: 36 ---
[[8 0 2 0]
 [8 0 0 0]
 [4 2 0 0]
 [0 0 0 0]]

--- St