In [5]:
from game import Game2048, Action
import numpy as np

config = {
    'grid_size': 4,
    'tile_2_probability': 0.9,
    'initial_tiles': 2,
    'random_seed': 42,
}
game = Game2048(config)

step = 0
while not game.is_game_over():
    available = game.get_available_moves()
    if not available:
        break

    action = np.random.choice(available)
    valid, reward = game.move(action)
    step += 1

    print(f"--- Step {step} | Action: {action.name} | Reward: {reward} | Score: {game.get_score()} ---")
    print(game.get_state())
    print()

print(f"Game Over! Final Score: {game.get_score()} in {step} steps")

--- Step 1 | Action: UP | Reward: 0 | Score: 0 ---
[[0 0 2 2]
 [0 0 2 0]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 2 | Action: LEFT | Reward: 4 | Score: 4 ---
[[4 0 0 0]
 [2 0 0 0]
 [2 0 0 0]
 [0 0 0 0]]

--- Step 3 | Action: UP | Reward: 4 | Score: 8 ---
[[4 0 0 0]
 [4 2 0 0]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 4 | Action: RIGHT | Reward: 0 | Score: 8 ---
[[0 0 0 4]
 [0 0 4 2]
 [2 0 0 0]
 [0 0 0 0]]

--- Step 5 | Action: RIGHT | Reward: 0 | Score: 8 ---
[[0 0 0 4]
 [0 0 4 2]
 [0 0 0 2]
 [0 0 0 4]]

--- Step 6 | Action: DOWN | Reward: 4 | Score: 12 ---
[[0 0 0 0]
 [0 0 0 4]
 [0 0 0 4]
 [0 2 4 4]]

--- Step 7 | Action: RIGHT | Reward: 8 | Score: 20 ---
[[0 0 0 0]
 [0 0 0 4]
 [0 0 2 4]
 [0 0 2 8]]

--- Step 8 | Action: UP | Reward: 12 | Score: 32 ---
[[2 0 4 8]
 [0 0 0 8]
 [0 0 0 0]
 [0 0 0 0]]

--- Step 9 | Action: LEFT | Reward: 0 | Score: 32 ---
[[2 4 8 0]
 [8 0 0 0]
 [0 0 0 0]
 [0 2 0 0]]

--- Step 10 | Action: RIGHT | Reward: 0 | Score: 32 ---
[[0 2 4 8]
 [0 2 0 8]
 [0 0 0 0]
 [0 0 0 2]]

--- S